// <auto-generated />
using System;
using IceBackend.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IceBackend.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IceBackend.Domain.Entities.BootstrapToken", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasColumnType("text");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("TokenHash");

                    b.HasIndex("PlayerId");

                    b.ToTable("bootstrap_tokens", (string)null);
                });

            modelBuilder.Entity("IceBackend.Domain.Entities.CosmeticAsset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AssetVersion")
                        .HasColumnType("integer");

                    b.Property<string>("CosmeticType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("cosmetic_assets", (string)null);
                });

            modelBuilder.Entity("IceBackend.Domain.Entities.CosmeticAssetVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Architecture")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("CosmeticAssetId")
                        .HasColumnType("uuid");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MetadataJson");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("MetadataJson"), "gin");

                    b.HasIndex("Sha256Hash");

                    b.HasIndex("CosmeticAssetId", "Architecture")
                        .IsUnique();

                    b.ToTable("cosmetic_asset_versions", (string)null);
                });

            modelBuilder.Entity("IceBackend.Domain.Entities.ExternalAuth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("Provider", "ExternalId")
                        .IsUnique();

                    b.ToTable("player_external_auth", (string)null);
                });

            modelBuilder.Entity("IceBackend.Domain.Entities.PaymentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentIntentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawEvent")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ProviderEventId")
                        .IsUnique();

                    b.ToTable("payment_events", (string)null);
                });

            modelBuilder.Entity("IceBackend.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("SessionHash")
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UuidType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("IceBackend.Domain.Entities.PlayerCosmetic", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Slot")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<Guid?>("CosmeticId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EquippedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PlayerId", "Slot");

                    b.HasIndex("CosmeticId");

                    b.ToTable("player_cosmetics", (string)null);
                });

            modelBuilder.Entity("IceBackend.Domain.Entities.PlayerCosmeticOwnership", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CosmeticId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderPaymentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PlayerId", "CosmeticId");

                    b.HasIndex("CosmeticId");

                    b.ToTable("player_cosmetic_ownership", (string)null);
                });

            modelBuilder.Entity("IceBackend.Domain.Entities.BootstrapToken", b =>
                {
                    b.HasOne("IceBackend.Domain.Entities.Player", "Player")
                        .WithMany("BootstrapTokens")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("IceBackend.Domain.Entities.CosmeticAssetVersion", b =>
                {
                    b.HasOne("IceBackend.Domain.Entities.CosmeticAsset", "CosmeticAsset")
                        .WithMany("Versions")
                        .HasForeignKey("CosmeticAssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CosmeticAsset");
                });

            modelBuilder.Entity("IceBackend.Domain.Entities.ExternalAuth", b =>
                {
                    b.HasOne("IceBackend.Domain.Entities.Player", "Player")
                        .WithMany("ExternalAuths")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("IceBackend.Domain.Entities.PaymentEvent", b =>
                {
                    b.HasOne("IceBackend.Domain.Entities.Player", "Player")
                        .WithMany("PaymentEvents")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("IceBackend.Domain.Entities.PlayerCosmetic", b =>
                {
                    b.HasOne("IceBackend.Domain.Entities.CosmeticAsset", "Cosmetic")
                        .WithMany()
                        .HasForeignKey("CosmeticId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IceBackend.Domain.Entities.Player", "Player")
                        .WithMany("EquippedCosmetics")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cosmetic");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("IceBackend.Domain.Entities.PlayerCosmeticOwnership", b =>
                {
                    b.HasOne("IceBackend.Domain.Entities.CosmeticAsset", "Cosmetic")
                        .WithMany("Ownerships")
                        .HasForeignKey("CosmeticId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IceBackend.Domain.Entities.Player", "Player")
                        .WithMany("CosmeticOwnerships")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cosmetic");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("IceBackend.Domain.Entities.CosmeticAsset", b =>
                {
                    b.Navigation("Ownerships");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("IceBackend.Domain.Entities.Player", b =>
                {
                    b.Navigation("BootstrapTokens");

                    b.Navigation("CosmeticOwnerships");

                    b.Navigation("EquippedCosmetics");

                    b.Navigation("ExternalAuths");

                    b.Navigation("PaymentEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
