// <auto-generated />
using System;
using IceBackend.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IceBackend.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260524214058_AddPlayerWearablesColumns")]
    partial class AddPlayerWearablesColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IceBackend.Domain.Entities.BootstrapToken", b =>
                {
                    b.Property<string>("TokenHash")
                        .HasColumnType("text");

                    b.Property<string>("Context")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("TokenHash");

                    b.HasIndex("PlayerId");

                    b.ToTable("bootstrap_tokens", (string)null);
                });

            modelBuilder.Entity("IceBackend.Domain.Entities.CosmeticAsset", b =>
                {
                    b.Property<int>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("internal_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InternalId"));

                    b.Property<int>("AssetVersion")
                        .HasColumnType("integer");

                    b.Property<string>("CosmeticType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("InternalId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("cosmetic_assets", (string)null);
                });

            modelBuilder.Entity("IceBackend.Domain.Entities.CosmeticAssetVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Architecture")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("CosmeticAssetInternalId")
                        .HasColumnType("integer")
                        .HasColumnName("cosmetic_asset_internal_id");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Sha256Hash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MetadataJson");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("MetadataJson"), "gin");

                    b.HasIndex("Sha256Hash");

                    b.HasIndex("CosmeticAssetInternalId", "Architecture")
                        .IsUnique();

                    b.ToTable("cosmetic_asset_versions", (string)null);
                });

            modelBuilder.Entity("IceBackend.Domain.Entities.ExternalAuth", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LinkedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("Provider", "ExternalId")
                        .IsUnique();

                    b.ToTable("player_external_auth", (string)null);
                });

            modelBuilder.Entity("IceBackend.Domain.Entities.PaymentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentIntentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawEvent")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ProviderEventId")
                        .IsUnique();

                    b.ToTable("payment_events", (string)null);
                });

            modelBuilder.Entity("IceBackend.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EquippedCapeId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipped_cape_uuid");

                    b.Property<Guid?>("EquippedHatId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipped_hat_uuid");

                    b.Property<Guid?>("EquippedPantsId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipped_pants_uuid");

                    b.Property<Guid?>("EquippedShirtId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipped_shirt_uuid");

                    b.Property<Guid?>("EquippedShoesId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipped_shoes_uuid");

                    b.Property<Guid?>("EquippedWingId")
                        .HasColumnType("uuid")
                        .HasColumnName("equipped_wing_uuid");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<bool>("RequiresSessionSync")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("requires_session_sync");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UuidType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int?>("_equippedCapeInternalId")
                        .HasColumnType("integer")
                        .HasColumnName("equipped_cape_id");

                    b.Property<int?>("_equippedHatInternalId")
                        .HasColumnType("integer")
                        .HasColumnName("equipped_hat_id");

                    b.Property<int?>("_equippedPantsInternalId")
                        .HasColumnType("integer")
                        .HasColumnName("equipped_pants_id");

                    b.Property<int?>("_equippedShirtInternalId")
                        .HasColumnType("integer")
                        .HasColumnName("equipped_shirt_id");

                    b.Property<int?>("_equippedShoesInternalId")
                        .HasColumnType("integer")
                        .HasColumnName("equipped_shoes_id");

                    b.Property<int?>("_equippedWingInternalId")
                        .HasColumnType("integer")
                        .HasColumnName("equipped_wing_id");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("_equippedCapeInternalId");

                    b.HasIndex("_equippedHatInternalId");

                    b.HasIndex("_equippedPantsInternalId");

                    b.HasIndex("_equippedShirtInternalId");

                    b.HasIndex("_equippedShoesInternalId");

                    b.HasIndex("_equippedWingInternalId");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("IceBackend.Domain.Entities.PlayerCosmeticOwnership", b =>
                {
                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("CosmeticAssetInternalId")
                        .HasColumnType("integer")
                        .HasColumnName("cosmetic_asset_internal_id");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProviderPaymentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PlayerId", "CosmeticAssetInternalId");

                    b.HasIndex("CosmeticAssetInternalId");

                    b.ToTable("player_cosmetic_ownership", (string)null);
                });

            modelBuilder.Entity("IceBackend.Domain.Entities.PlayerSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccumulatedMonths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("AccumulatedMonths");

                    b.Property<bool>("AutoRenew")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("AutoRenew");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ExpiresAt");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("IsActive");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("StripeSubscriptionId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("StripeSubscriptionId");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("player_subscriptions", (string)null);
                });

            modelBuilder.Entity("IceBackend.Domain.Entities.UnresolvedPaymentEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentIntentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawEvent")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProviderEventId")
                        .IsUnique();

                    b.ToTable("unresolved_payment_events", (string)null);
                });

            modelBuilder.Entity("IceBackend.Domain.Entities.BootstrapToken", b =>
                {
                    b.HasOne("IceBackend.Domain.Entities.Player", "Player")
                        .WithMany("BootstrapTokens")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("IceBackend.Domain.Entities.CosmeticAssetVersion", b =>
                {
                    b.HasOne("IceBackend.Domain.Entities.CosmeticAsset", "CosmeticAsset")
                        .WithMany("Versions")
                        .HasForeignKey("CosmeticAssetInternalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CosmeticAsset");
                });

            modelBuilder.Entity("IceBackend.Domain.Entities.ExternalAuth", b =>
                {
                    b.HasOne("IceBackend.Domain.Entities.Player", "Player")
                        .WithMany("ExternalAuths")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("IceBackend.Domain.Entities.PaymentEvent", b =>
                {
                    b.HasOne("IceBackend.Domain.Entities.Player", "Player")
                        .WithMany("PaymentEvents")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("IceBackend.Domain.Entities.Player", b =>
                {
                    b.HasOne("IceBackend.Domain.Entities.CosmeticAsset", null)
                        .WithMany()
                        .HasForeignKey("_equippedCapeInternalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IceBackend.Domain.Entities.CosmeticAsset", null)
                        .WithMany()
                        .HasForeignKey("_equippedHatInternalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IceBackend.Domain.Entities.CosmeticAsset", null)
                        .WithMany()
                        .HasForeignKey("_equippedPantsInternalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IceBackend.Domain.Entities.CosmeticAsset", null)
                        .WithMany()
                        .HasForeignKey("_equippedShirtInternalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IceBackend.Domain.Entities.CosmeticAsset", null)
                        .WithMany()
                        .HasForeignKey("_equippedShoesInternalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("IceBackend.Domain.Entities.CosmeticAsset", null)
                        .WithMany()
                        .HasForeignKey("_equippedWingInternalId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("IceBackend.Domain.Entities.PlayerCosmeticOwnership", b =>
                {
                    b.HasOne("IceBackend.Domain.Entities.CosmeticAsset", "Cosmetic")
                        .WithMany("Ownerships")
                        .HasForeignKey("CosmeticAssetInternalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IceBackend.Domain.Entities.Player", "Player")
                        .WithMany("CosmeticOwnerships")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cosmetic");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("IceBackend.Domain.Entities.PlayerSubscription", b =>
                {
                    b.HasOne("IceBackend.Domain.Entities.Player", "Player")
                        .WithOne("Subscription")
                        .HasForeignKey("IceBackend.Domain.Entities.PlayerSubscription", "PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("IceBackend.Domain.Entities.CosmeticAsset", b =>
                {
                    b.Navigation("Ownerships");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("IceBackend.Domain.Entities.Player", b =>
                {
                    b.Navigation("BootstrapTokens");

                    b.Navigation("CosmeticOwnerships");

                    b.Navigation("ExternalAuths");

                    b.Navigation("PaymentEvents");

                    b.Navigation("Subscription");
                });
#pragma warning restore 612, 618
        }
    }
}
